name: Deploy to Amazon ECS

on:
  workflow_dispatch: {}

env:
  AWS_REGION: us-west-2
  ECR_REPOSITORY: my-ecr-repo

jobs:
  deploy_ecr_ecs:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      issues: write
      pull-requests: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install AWS CLI
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install --update
    - name: Install jq
      run: sudo apt-get install jq

    - name: Configure AWS credentials with GitHub token provider
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.IAMROLE_GITHUB }}
        role-session-name: GitHub-Action-Role
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Get AWS Account ID
      id: aws_account_id
      run: echo "::set-output name=aws_account_id::$(aws sts get-caller-identity --query Account --output text)"

    - name: Get short SHA
      id: get_short_sha
      run: echo "::set-output name=sha_short::$(echo ${GITHUB_SHA::4})"
      env:
        GITHUB_SHA: ${{ github.sha }}

    - name: Build and push Docker image
      id: build-push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ steps.aws_account_id.outputs.aws_account_id }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ steps.get_short_sha.outputs.sha_short }}

    - name: Render Amazon ECS task definition
      id: render-web-container
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task-definition.json
        container-name: my-container
        image: ${{ steps.aws_account_id.outputs.aws_account_id }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ steps.get_short_sha.outputs.sha_short }}

    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.render-web-container.outputs.task-definition }}
        service: my-service
        cluster: my-cluster
