name: Upload to Amazon S3

on:
  workflow_dispatch: {}

env:
  AWS_REGION: us-west-2

jobs:
  sync_to_s3:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install AWS CLI
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install --update

    - name: Install jq
      run: sudo apt-get install jq

    - name: Configure AWS credentials with GitHub token provider
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.IAMROLE_GITHUB }}
        role-session-name: GitHub-Action-Role
        aws-region: ${{ env.AWS_REGION }}

    - name: Read bucket name from secret
      run: echo "BUCKET_NAME=$(echo "my-s3-bucket-from-github-action")" >> $GITHUB_ENV

    - name: Sync files to S3 bucket
      run: aws s3 sync . s3://${{ env.BUCKET_NAME }}

    - name: Zip the contents of the S3 bucket
      run: |
        TIMESTAMP=$(date '+%Y-%m-%d-%H-%M-%S')
        ZIP_NAME="website-files-${TIMESTAMP}.zip"
        aws s3 cp "s3://${{ env.BUCKET_NAME }}" "s3://${{ env.BUCKET_NAME }}/${ZIP_NAME}" --no-recursive

    - name: Print the URL of the zipped files
      run: |
        echo "Zipped files URL: https://s3.${AWS_REGION}.amazonaws.com/${{ env.BUCKET_NAME }}/${ZIP_NAME}"
